### PR TITLE
VENDOR_CWD_RAW_DATA policy for kernel >= 5.3.0

### LINKED ISSUE #421: [v5.6.4.1][linux-5.3.1]: WARNING: CPU: 1 PID: 42 at net/wireless/core.c:868 wiphy_register.cold+0x37/0x435 [cfg80211]
Hello,

The v5.6.4.1 88XXau driver appears to be crashing while attempting to register an 8811 device (marketed as the "EDUP 802.11ac USB WiFi Dongle", serial = 00e04c000001). This is on an Arch Linux kernel (version 5.3.1). I installed the driver using dkms-install.sh.

```
WARNING: CPU: 1 PID: 42 at net/wireless/core.c:868 wiphy_register.cold+0x37/0x435 [cfg80211]
...
[  511.028685] Call Trace:                                                      
[  511.028701]  ? preempt_count_add+0x68/0xa0                                   
[  511.028803]  rtw_wiphy_register+0x16/0x18 [88XXau]                           
[  511.028901]  rtw_cfg80211_ndev_res_register+0x11/0x17 [88XXau]               
[  511.028992]  rtw_os_ndev_register+0xe3/0x14c [88XXau]                        
[  511.029085]  rtw_os_ndevs_register+0x9a/0xfb [88XXau]                        
[  511.029176]  rtw_os_ndevs_init+0x24/0x38 [88XXau]                            
[  511.029266]  rtw_drv_init+0x2b3/0x376 [88XXau]                               
[  511.029275]  usb_probe_interface+0xe0/0x280 
```

Additional dmesg output attached -- there are two more (apparently related) call traces:

```
WARNING: CPU: 1 PID: 42 at /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/os_intfs.c:1605 rtw_os_ndev_register+0xaa/0x14c [88XXau]
...
WARNING: CPU: 1 PID: 42 at /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/os_intfs.c:3039 rtw_os_ndevs_register+0xd1/0xfb [88XXau]
```

[latest-dmesg.txt](https://github.com/aircrack-ng/rtl8812au/files/3640281/latest-dmesg.txt)

Thanks for taking a look.

### PR DESCRIPTION
**Pull request by hexc0de**
Resolves #421

### CODE REVIEW

**Comment by CGarces** [comment]
I'm confused #421 is about v5.6.4.1
Are you sure that the patch fix the issue? v5.6.4.1 already has that change.
Are you sure the you want merge to V5.3.4?
The branches  v5.6.4.1 (last one) and v5.2.20 (considered stable) are already patched for kernel 5.3 (see #430)

**Comment by hexc0de** [comment]
Yeasterday I did this changes on local machine, rebuilt with dkms and my wi-fi usb dongle (on chip 8811) worked again on version 5.3.4

**Comment by hexc0de** [comment]
Already tried v5.6.4.1 and got dmesg lines as in #421 .
Please, look at https://github.com/aircrack-ng/rtl8812au/blob/v5.6.4.1/os_dep/linux/rtw_cfgvendor.c#L1907 and https://github.com/aircrack-ng/rtl8812au/blob/v5.2.20/os_dep/linux/rtw_cfgvendor.c#L1447
Symbol at the end of line "æ", it should not be here.

**Comment by CGarces** [comment]
Thanks @hexc0de good catch.
I have send PRs #434 and #433

**Comment by christosvar** [comment]
I tried removing the special character locally, and I still got the same error reported in issue 421. (v5.6.4.1, chip rtl8812au)

**Comment by terencode** [comment]
@hexc0de unfortunately it does not look like this symbol is causing #421, I applied #433 and still see it.

**Pull request merged**
