### PR TITLE
Update to kernel 4.19

### PR DESCRIPTION
**Pull request by darkdragon-001**
Applying patch from [gordboy/rtl8812au](https://github.com/gordboy/rtl8812au).

### CODE REVIEW

**Comment by darkdragon-001** [comment]
This patch should be applied to all versions/branches.

**Comment by kimocoder** [comment]
Tested and working? will have a look in few days anyway

**Comment by darkdragon-001** [comment]
It compiles (on kernel 4.19 which was not possible before) and I can connect to a network. That's all I tested so far...

**Comment by kimocoder** [comment]
waiting for Kali kernel update to stable v4.19 before testing/pushing this one

**Comment by kimocoder** [comment]
Updated the kernel v4.19 support with gordboy's patch. Had to rework it duo to changes, but thanks for the PR anyway! Also, added kernel v4.20 support.

**Pull request closed without merging**
