### PR TITLE
Fix the null pointer dereference bug

### LINKED ISSUE #1076: No networks found
I recently installed `v5.6.4.2` with no errors. The adapter shows up in settings but its not finding any networks. I've tried an older version, re-installation, and enabling/disabling secure boot to no avail. I am using an `rtl8812AU 802.11ac`, `Ubuntu 22.04`, and `kernel version 5.19`.

### PR DESCRIPTION
**Pull request by n0tank3sh**
Fixes the null pointer dereference bug caused due to the cleanup.  
Potentially Closes: #1076 #1075  #1073 #1081 #1079

### CODE REVIEW

**Comment by LxtteDev** [comment]
This works.

**Comment by AmFartura3** [comment]
It's Works!

**Comment by juceda** [comment]
Unfortunately, it seems it does not work for me... -> [https://github.com/aircrack-ng/rtl8812au/issues/1081#issuecomment-1584887788](https://github.com/aircrack-ng/rtl8812au/issues/1081#issuecomment-1584887788)

**Comment by n0tank3sh** [comment]
@juceda Can you send the log after the compilation and loading of the driver with the patch applied? or maybe try a fresh install like https://github.com/aircrack-ng/rtl8812au/issues/1076#issuecomment-1575119492 which fixed their issue.

**Comment by juceda** [comment]
@MightiestGoat thank you for your answer. For sure I had the issue on past days, but today I was able to try, fully updated Fedora with pending updates also cloned the repo with the patch on a new folder and tried to make a clean install as you suggested. Now I can confirm the dongle is working again as expected!

> @juceda Can you send the log after the compilation and loading of the driver with the patch applied? or maybe try a fresh install like [#1076 (comment)](https://github.com/aircrack-ng/rtl8812au/issues/1076#issuecomment-1575119492) which fixed their issue.

**Comment by n0tank3sh** [comment]
Looks like @kimocoder  reverted those [changes]( https://github.com/aircrack-ng/rtl8812au/commit/ca797e114b0640d6aa1a573ea68526a9263df81e) so I am closing the pull request.

**Pull request closed without merging**
