### PR TITLE
add Edimax - EW-7811UnV2

### PR DESCRIPTION
**Pull request by aep**

### CODE REVIEW

**Comment by CGarces** [comment]
ping @hno and @aep

The vendor handle this id as  RTL8188E.

Vendor page:
https://www.edimax.com/edimax/download/download/data/edimax/global/download/wireless_adapters_n150/ew-7811un_v2

Source code:

`{USB_DEVICE(USB_VENDER_ID_EDIMAX, 0xB811), .driver_info = RTL8188E}, /* Edimax - Edimax */
`

I'm not use if set the ID as RTL8812 is correct.

**Comment by CGarces** [comment]
Note that on the Linux staging tree also is considered as RTL8188EU.

https://github.com/torvalds/linux/commit/7a8d2f1908a59003e55ef8691d09efb7fbc51625

**Comment by aep** [comment]
unclear, this driver worked for me in client mode only, so maybe that's related?
RTL8188EU doesnt work at all, but again, unclear. 
If in doubt, i'd assume upstream linux has done more testing than i did.

**Comment by CGarces** [comment]
Thanks for your feedback.
When you said RTL8188EU you are talking about RTL8188EU driver or about compile this driver moving the declaration to RTL8188E?
Sounds very strange that use the same approach than the [vendor driver](https://www.edimax.com/edimax/download/download/data/edimax/global/download/wireless_adapters_n150/ew-7811un_v2) not works.

**Comment by aep** [comment]
It might have been this one https://github.com/lwfinger/rtl8188eu

either way i never could any of the drivers working in ap mode so i just gave up.

> or about compile this driver moving the declaration to RTL8188E?

if it helps you, i can try that

**Comment by CGarces** [comment]
> if it helps you, i can try that

Yes please!.

**Pull request merged**
