### PR TITLE
Backported driver V5.9.3.2 changes and fixed all kernel warnings.... Also fixed Injection and monitor mode (except for fragmentation attacks, something still missing there)

### PR DESCRIPTION
**Pull request by ejtagle**
both monitor and managed modes work.
This is the ONLY driver that does not crash 5.4.x.x kernels when inserted or removed.

-Fixed airodump not displaying the signal power levels
-This STILL requires to iw to switch into monitor mode: 

sudo iw dev
sudo ip link set wlan0 down
sudo iw wlan0 set type monitor 
sudo ip link set wlan0 up

ONLY use ip/iw commands. DO NOT use iwconfig, as iwconfig, even if it seems to work, does not allow aircrack programs to control the channel frequency to monitor!

### CODE REVIEW

**Comment by Raikia** [comment]
This definitely works better than the existing driver for 5.4.x.x kernels, but with this driver, no matter what I do I'm getting "malformed packet" in wireshark when packet capturing.  So I think something is wrong here still.

**Comment by IGNNE** [comment]
When using this for Wifibroadcast (data over injection/monitor mode), I can confirm that I end up with no usable data on both ends. Also, a bunch of channels seem to be disabled (144 and up), although they should be allowed in my location.

**Comment by ejtagle** [comment]
I didn't test monitor mode, specifically, packet injection when on monitor mode... I guess the problem is exactly there (capture seems fine, though...) ... 

If you revert the changes i did to the file core/monitor/rtw_radiotap.c , that probably would fix wireshark captures, but, it makes airodump-ng not to properly display the power level of the networks it finds... Basically, seems the radiotap header is not properly parsed by wireshark, if too many information elements are present there...

Also in os_dep/linux/ioctl_cfg80211.c , line 2780, maybe needs to be reverted so wireshark "understands" the captured packets ... As far as i understand this, this line  informs the format of the captured packets, as dumped, and it should be radiotap, but, something maybe requires a different format here...

Regarding the missing wifi channels, revert the file os_dep/linux/wifi_regd.c  and you will get them back, but then, the linux kernel will "crash" when shutting down, because it validates the tables and does not like what it sees...

**Comment by ejtagle** [comment]
I have tested the driver both with aircrack suite (airodump-ng and aireplay-ng, and all tests except fragmentation tests pass. 
Wifite script works.
hcxdumptool also works and all tests pass

**Comment by ejtagle** [comment]
Please, could you test it now, @Raikia ? ... Now it works beautifully for me (no more 'malformed packets', WPA handshake properly captured. PKMID properly captured, no more kernel crashes... I really hope it will also work for you!

@IGNNE , could you also test it now, with the latest changes i push ? ... Previously, data capture was not working in monitor mode, but now it seems to work at least for me...

**Pull request closed without merging**
