### PR TITLE
Merge changes

### PR DESCRIPTION
**Pull request by kimocoder**
* Update kernel v4.19 support
* Add kernel v4.20 support and minor compiler warning turned off
* Fix problem where interfaces are down at start

**This commit is not finished up, adding more fixes before pushing to Kali**

### CODE REVIEW

**Comment by kimocoder** [comment]
* Fix problem where interfaces are down at start

**Comment by kimocoder** [comment]
I think we got it for now. Pushing to Kali repos shortly

**Comment by ChalesYu** [comment]
Branch v5.1.5 also need this kernel version patch , please add it , thanks .

**Comment by kimocoder** [comment]
It is pretty much deprecated, but I May do it anyways this weekend sometime

**Pull request merged**
