### PR TITLE
Merge USB identifiers from v5.6.4.2

### PR DESCRIPTION
**Pull request by hkroger**

### CODE REVIEW

**Comment by CGarces** [comment]
Hi @hkroger 

- Changes will be more easy to track if you sort the USB identifiers (by vendor and device). 
- Try to insert all with upper cases.
- Replace some 0x0BDA with USB_VENDER_ID_REALTEK

--Edit--
After sort and replace the 0x0BDA you can find some duplicates like
{USB_DEVICE(0x0BDA, 0xA811) or {USB_DEVICE(0x2001, 0x3313)

Please review this
https://gist.github.com/CGarces/40ecf4c6c55b49fc4e1958bee7833279

**Comment by hkroger** [comment]
Good point, I sorted those, removed duplicates and uppercased that last one identifier that I missed.

**Comment by hno** [comment]
Is this intentional?

-  {USB_DEVICE(0x7392, 0xb811), .driver_info = RTL8812}, /* Edimax - EW-7811UnV2 */

**Comment by CGarces** [comment]
Hi @hno
Looks bad. Several ids are affected.
For example {USB_DEVICE(0x7392, 0xA812), .driver_info = RTL8821} has changed to .driver_info = RTL8821}

https://gist.github.com/CGarces/40ecf4c6c55b49fc4e1958bee7833279 should work, but I haven't check the diffs with the current version, fell free to send a PR, in any case I'll send a fix tonight (CET)

Default branch (v5.6.4.2) are not affected.

**Comment by hkroger** [comment]
@CGarces I don't follow now.

v5.6.4.2:
` 	{USB_DEVICE(0x7392, 0xA812), .driver_info = RTL8821}, /* Edimax - EW-7811UTC */`

v5.7.0:
`  {USB_DEVICE(0x7392, 0xA812), .driver_info = RTL8812}, /* Edimax - EW-7811UTC */`

In this PR that of 5.7.0 is changed to that what is in 5.6.4.2. Which one is right?

**Comment by hkroger** [comment]
> Is this intentional?
> 
> * {USB_DEVICE(0x7392, 0xb811), .driver_info = RTL8812}, /* Edimax - EW-7811UnV2 */

This is missing in v5.6.4.2 but can be left in place if that's still needed/used.

**Comment by CGarces** [comment]
> @CGarces I don't follow now.
> 
> v5.6.4.2:
> ` {USB_DEVICE(0x7392, 0xA812), .driver_info = RTL8821}, /* Edimax - EW-7811UTC */`
> 
> v5.7.0:
> ` {USB_DEVICE(0x7392, 0xA812), .driver_info = RTL8812}, /* Edimax - EW-7811UTC */`
> 
> In this PR that of 5.7.0 is changed to that what is in 5.6.4.2. Which one is right?

v5.6.4.2 is right.

**Comment by hkroger** [comment]
> > @CGarces I don't follow now.
> > v5.6.4.2:
> > ` {USB_DEVICE(0x7392, 0xA812), .driver_info = RTL8821}, /* Edimax - EW-7811UTC */`
> > v5.7.0:
> > ` {USB_DEVICE(0x7392, 0xA812), .driver_info = RTL8812}, /* Edimax - EW-7811UTC */`
> > In this PR that of 5.7.0 is changed to that what is in 5.6.4.2. Which one is right?
> 
> v5.6.4.2 is right.

Ok, so this PR should fix it already, right?

**Comment by CGarces** [comment]
Sorry but I don't have free time now and I'm checking the code directly with web interface, without pay much attention.
Probably my previous comments are not 100% correct.

I said that V5.6.4.2 was correct based on my 1º search on google.
Now I have checked the driver provided by the vendor...

https://www.edimax.com/edimax/merchandise/merchandise_detail/data/edimax/global/wireless_adapters_ac600_dual-band/ew-7811utc/

And with the driver provided by the vendor...

{USB_DEVICE(0x7392, 0xA812), .driver_info = RTL8821}, /* Edimax - Edimax */

So yes, your PR maybe fix some unknown problems on V.5.7.0 

About the missing id, I have put a comment in the PR  #805

**Pull request closed without merging**
