### PR TITLE
Add support for pre-configured SeqNum via RadioTap

### PR DESCRIPTION
**Pull request by dpShaker**
See http://www.radiotap.org/fields/TX%20flags value 0x0010

### CODE REVIEW

**Comment by kimocoder** [comment]
Great work sir, looks good. Merged.

**Comment by kimocoder** [comment]
@dpShaker could you add this to v4.3.21 branch too? again, thanks!

**Comment by dpShaker** [comment]
@kimocoder I can take care of it in a few weeks, only. But I saw you did already some changes on v4.3.21 but reverted them. What's the rationale? Have you identified issues?

**Comment by kimocoder** [comment]
Yes encountered few issues with compiling. Have a look at it when you got time.
There are also 2 other issues that needs some attention, the most important would be [this](https://github.com/aircrack-ng/rtl8812au/issues/28) and the fact that USB3 (modeswitch) reported [here](https://github.com/aircrack-ng/rtl8812au/issues/29)

**Comment by kimocoder** [comment]
@dpShaker No need to continue on v4.3.21 anyway, v5.1.5 should absolutely be in focus. Thanks.

**Pull request merged**
