### PR TITLE
Local build feed for OpenWrt

### PR DESCRIPTION
**Pull request by stepheny**
Should the doc be in a separate file?
Or should this patch be in a separate git repo?

### CODE REVIEW

**Comment by lesavonfou** [comment]
Hi,

I tested your recipe and it seems to work on the latest OpenWRT branch targeting a Raspberry PI 3B! 👍 
I was wondering why did you use:

    PKG_SOURCE_URL:=file://$(shell realpath ../..)

and

    PKG_SOURCE_VERSION:=$(shell git rev-parse HEAD)


for retrieving the sourc;es?

**Comment by llccd** [comment]
OpenWrt uses backported mac80211. If the kernel version and mac80211 version is different, build errors may happen. Currently the version is both 5.4, so we can build without issue.

**Comment by lesavonfou** [comment]
@llccd Does this mean that the recipe may not be valid over time due to incompatibility with the backport of mac80211?

If so, is the backport specifically made and managed by OpenWRT?

**Comment by llccd** [comment]
Yes. But not made nor managed by OpenWRT. You can get more info at https://backports.wiki.kernel.org/index.php/Main_Page

**Comment by lesavonfou** [comment]
Thanks for the link.

A decision needs to be made here. I see two scenarios:
- A fork/branch per backport version which is going to keep in sync as much as possible the two projects.
- An integration of the backport changes through, for example, a macro (-DBACKPORT_VERSION_XXX).

I am not involved in this project enough to tell which direction should be taken.

**Comment by llccd** [comment]
@lesavonfou Taking https://github.com/greearb/ath10k-ct as a reference, they used the first option you mentioned.

But I prefer to add a macro with backport version like `BACKPORT_VERSION_CODE` and implement version check like `BACKPORT_VERSION_CODE < KERNEL_VERSION(x, x, xx)` in related cfg80211 code. If there is no backport we simply can make `BACKPORT_VERSION_CODE = LINUX_VERSION_CODE`

**Comment by ghost** [comment]
Hi,
I tested and works well on x86 and Raspberry PI 4 .


> A decision needs to be made here. I see two scenarios:

@lesavonfou  I agree on this , maybe @stepheny can make a PR on OpenWrt

**Comment by stepheny** [comment]
> Hi,
> 
> I tested your recipe and it seems to work on the latest OpenWRT branch targeting a Raspberry PI 3B! 
> I was wondering why did you use:
> 
> ```
> PKG_SOURCE_URL:=file://$(shell realpath ../..)
> ```
> 
> and
> 
> ```
> PKG_SOURCE_VERSION:=$(shell git rev-parse HEAD)
> ```
> 
> for retrieving the sourc;es?

This is due to the process OpenWrt build a package. OpenWrt buildroot will always fetch a source package from somewhere or cache, then unpack or checkout into a clean temporary directory to build. This might sound tedious but really make sense in a package build system. Although it is possile to instruct OpenWrt SDK to fetch(make an arhive of) source code from a working directory, this would bypass versioning of the system and it would be user's duty to manually invoke prepare stage and manipulate empty target files to inform build system an source code update. Since we already have a local git repository, why not use it. As a side effect, we need to commit before build.
This build feed do not need to be in source tree at all. Change `PKG_SOURCE_URL` and `PKG_SOURCE_PROTO` to any where your source code is, it works just fine with github. In case of git, `PKG_SOURCE_VERSION` is supposed to be a commit id. This is necessary for the build system to make reproducible packages.

**Comment by stepheny** [comment]
> Hi,
> I tested and works well on x86 and Raspberry PI 4 .
> 
> > A decision needs to be made here. I see two scenarios:
> 
> @lesavonfou I agree on this , maybe @stepheny can make a PR on OpenWrt

I'm so glad it works!
I'm not so confidence this is ready for upstream.
As far as I know, in OpenWrt there is no proper way to config auto-load module parameter, neither in package building scripts. So a patch in this feed changed the default value of `rtw_vht_enalbe` to `2`(force auto enable) and `rtw_switch_usb_mode` to `1`(switch from usb2.0 to usb 3.0). Although this seems reasonable, on some specific harware wlan 5G channels interfere with usb3.0 severely. It is almost impossible for a normal user to disable it.
By the way, in EXPERIMENTAL branch, get/set txpower do not work either.

**Comment by castillofrancodamian** [comment]
Thank you all!

**Comment by Menion2k** [comment]
> Hi,
> I tested and works well on x86 and Raspberry PI 4 .
> 
> > A decision needs to be made here. I see two scenarios:
> 
> @lesavonfou I agree on this , maybe @stepheny can make a PR on OpenWrt

Hi

I have tried your PR, but the drivers has trouble in working in AP, when selecting AC mode
Also I have tried to step after the last commit of this driver but then during the compilation I get:

`  CC [M]  /media/storage/das1/temp/openwrt_rpi4/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/rtl8812au-ac-2020-07-12-afb5c175/core/rtw_cmd.o
cc1: error: unknown value 'native' for -mtune
cc1: note: valid arguments are: cortex-a35 cortex-a53 cortex-a57 cortex-a72 cortex-a73 thunderx thunderxt88p1 thunderxt88 thunderxt81 thunderxt83 xgene1 falkor qdf24xx exynos-m1 thunderx2t99p1 vulcan thunderx2t99 cortex-a55 cortex-a75 cortex-a76 ares neoverse-n1 saphira cortex-a57.cortex-a53 cortex-a72.cortex-a53 cortex-a73.cortex-a35 cortex-a73.cortex-a53 cortex-a75.cortex-a55 generic
`

which is somhow strange since the Makefile does not apper to have changed so much

**Comment by aep** [comment]
was this ever moved to a stable branch?

**Comment by CanadianJeff** [comment]
+1 I also would like to know because I have https://deviwiki.com/wiki/TP-LINK_Archer_T2U_Plus which uses the RTL8812AU and an x86_64 openwrt router (PCEngines APU2) created a forum post at https://forum.openwrt.org/t/tp-link-ac600-archer-t2u-plus-drivers/85300

**Comment by aep** [comment]
I got it compiled but it just results in kernel freeze

**Comment by CanadianJeff** [comment]
could you share your compiled binaries with me so I can test them on my APU2? which is x86_64 based cpu would really like the help my APU2 kernel version is a bit older

```
root@APU2:/etc/config# cat /etc/banner
  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 19.07.5, r11257-5090152ae3
 -----------------------------------------------------
root@APU2:/etc/config# uname -a
Linux APU2 4.14.209 #0 SMP Sun Dec 6 07:31:03 2020 x86_64 GNU/Linux
root@APU2:/etc/config# lsmod | grep rtl
btcoexist             118784  1 rtl8821ae
cfg80211              225280  8 ath9k,ath9k_common,ath,rtlwifi,rtl8812au,rtl818x_pci,rtl8187,mac80211
compat                 12288 14 ath9k,ath9k_common,rtl8821ae,rtl8192se,rtl8192de,rtl8192cu,rtl8192ce,btcoexist,rtlwifi,rtl8xxxu,rtl818x_pci,rtl8187,mac80211,cfg80211
eeprom_93cx6           12288  2 rtl818x_pci,rtl8187
mac80211              409600 11 ath9k,rtl8821ae,rtl8192se,rtl8192cu,rtl8192ce,rtl_usb,rtl_pci,rtlwifi,rtl8xxxu,rtl818x_pci,rtl8187
rtl_pci                24576  4 rtl8821ae,rtl8192se,rtl8192de,rtl8192ce
rtl_usb                16384  1 rtl8192cu
rtl8187                36864  0
rtl818x_pci            45056  0
rtl8192c_common        36864  2 rtl8192cu,rtl8192ce
rtl8192ce              53248  0
rtl8192cu              61440  0
rtl8192de              98304  0
rtl8192se              57344  0
rtl8812au            1155072  0
rtl8821ae             204800  0
rtl8xxxu               90112  0
rtlwifi                57344  9 rtl8821ae,rtl8192se,rtl8192de,rtl8192cu,rtl8192ce,rtl8192c_common,rtl_usb,rtl_pci,btcoexist
root@APU2:/etc/config# dmesg | grep rtl
[   10.757732] usbcore: registered new interface driver rtl8187
[   10.920495] RTL871X: rtl8812au v4.3.14_13455.20150212_BTCOEX20150128-51
[   10.927130] RTL871X: rtl8812au BT-Coex version = BTCOEX20150128-51
[   10.933493] usbcore: registered new interface driver rtl8812au
[   10.945267] usbcore: registered new interface driver rtl8xxxu
[   10.977091] usbcore: registered new interface driver rtl8192cu
```
```
root@APU2:/etc/config# find /lib -type f -name 'rtl*'
/lib/firmware/rtl_nic/rtl8105e-1.fw
/lib/firmware/rtl_nic/rtl8106e-1.fw
/lib/firmware/rtl_nic/rtl8106e-2.fw
/lib/firmware/rtl_nic/rtl8107e-1.fw
/lib/firmware/rtl_nic/rtl8107e-2.fw
/lib/firmware/rtl_nic/rtl8168d-1.fw
/lib/firmware/rtl_nic/rtl8168d-2.fw
/lib/firmware/rtl_nic/rtl8168e-1.fw
/lib/firmware/rtl_nic/rtl8168e-2.fw
/lib/firmware/rtl_nic/rtl8168e-3.fw
/lib/firmware/rtl_nic/rtl8168f-1.fw
/lib/firmware/rtl_nic/rtl8168f-2.fw
/lib/firmware/rtl_nic/rtl8168g-1.fw
/lib/firmware/rtl_nic/rtl8168g-2.fw
/lib/firmware/rtl_nic/rtl8168g-3.fw
/lib/firmware/rtl_nic/rtl8168h-1.fw
/lib/firmware/rtl_nic/rtl8168h-2.fw
/lib/firmware/rtl_nic/rtl8402-1.fw
/lib/firmware/rtl_nic/rtl8411-1.fw
/lib/firmware/rtl_nic/rtl8411-2.fw
/lib/firmware/rtlwifi/rtl8192cfw.bin
/lib/firmware/rtlwifi/rtl8192cfwU.bin
/lib/firmware/rtlwifi/rtl8192cfwU_B.bin
/lib/firmware/rtlwifi/rtl8192cufw.bin
/lib/firmware/rtlwifi/rtl8192cufw_A.bin
/lib/firmware/rtlwifi/rtl8192cufw_B.bin
/lib/firmware/rtlwifi/rtl8192cufw_TMSC.bin
/lib/firmware/rtlwifi/rtl8192defw.bin
/lib/firmware/rtlwifi/rtl8192sefw.bin
/lib/firmware/rtlwifi/rtl8821aefw.bin
/lib/firmware/rtlwifi/rtl8821aefw_wowlan.bin
/lib/modules/4.14.209/rtlwifi.ko
/lib/modules/4.14.209/rtl_usb.ko
/lib/modules/4.14.209/rtl8812au.ko
/lib/modules/4.14.209/rtl818x_pci.ko
/lib/modules/4.14.209/rtl8187.ko
/lib/modules/4.14.209/rtl8192c-common.ko
/lib/modules/4.14.209/rtl_pci.ko
/lib/modules/4.14.209/rtl8192ce.ko
/lib/modules/4.14.209/rtl8192cu.ko
/lib/modules/4.14.209/rtl8192de.ko
/lib/modules/4.14.209/rtl8192se.ko
/lib/modules/4.14.209/rtl8821ae.ko
/lib/modules/4.14.209/rtl8xxxu.ko
```

**Comment by aquaforum** [comment]
Hello.
Please tell me how to build it for openwrt (mt7621a) ? 
I need makefile for openwrt sdk
I can build simple programs using SDK, but I can't build a kernel module
Thanks￼

**Comment by castillofrancodamian** [comment]
@aquaforum They have deleted the changes added in this pull request and I don't see anything from OpenWrt in this repository.

**Pull request merged**
