### PR TITLE
bugfix: Wrap newer construct to allow build on kernel <4.18

### PR DESCRIPTION
**Pull request by Hurricos**
As per https://github.com/aircrack-ng/rtl8812au/issues/676.

### CODE REVIEW

**Comment by Hurricos** [comment]
I'm not sure if this is correct per se, but it certainly builds fine.

**Comment by kimocoder** [comment]
Merged. Thanks!

**Comment by wideace99** [comment]
Hello.
Still not working with kernel <4.18
In my case I use kernel 4.9

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.9.0-13-amd64/build M=/root/rtl8812au/rtl8812au  modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.0-13-amd64'
  CC [M]  /root/rtl8812au/rtl8812au/core/rtw_cmd.o
gcc-6: error: unrecognized command line option ‘-Wimplicit-fallthrough=0’; did you mean ‘-Wno-fallthrough’?
/usr/src/linux-headers-4.9.0-13-common/scripts/Makefile.build:309: recipe for target '/root/rtl8812au/rtl8812au/core/rtw_cmd.o' failed
make[4]: *** [/root/rtl8812au/rtl8812au/core/rtw_cmd.o] Error 1
/usr/src/linux-headers-4.9.0-13-common/Makefile:1560: recipe for target '_module_/root/rtl8812au/rtl8812au' failed
make[3]: *** [_module_/root/rtl8812au/rtl8812au] Error 2
Makefile:152: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.0-13-amd64'
Makefile:2246: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by Hurricos** [comment]
You're using gcc-6 is the problem.

**Comment by wideace99** [comment]
How can I change the gcc version ?

`root@smtp:~/rtl8812au/rtl8812au#` gcc --version
gcc (GCC) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@smtp:~/rtl8812au/rtl8812au#` make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.9.0-13-amd64/build M=/root/rtl8812au/rtl8812au  modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.0-13-amd64'
  CC [M]  /root/rtl8812au/rtl8812au/core/rtw_cmd.o
gcc-6: error: unrecognized command line option ‘-Wimplicit-fallthrough=0’; did you mean ‘-Wno-fallthrough’?
/usr/src/linux-headers-4.9.0-13-common/scripts/Makefile.build:309: recipe for target '/root/rtl8812au/rtl8812au/core/rtw_cmd.o' failed
make[4]: *** [/root/rtl8812au/rtl8812au/core/rtw_cmd.o] Error 1
/usr/src/linux-headers-4.9.0-13-common/Makefile:1560: recipe for target '_module_/root/rtl8812au/rtl8812au' failed
make[3]: *** [_module_/root/rtl8812au/rtl8812au] Error 2
Makefile:152: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.0-13-amd64'
Makefile:2246: recipe for target 'modules' failed
make: *** [modules] Error 2
root@smtp:~/rtl8812au/rtl8812au`

**Pull request merged**
