### PR TITLE
Add RTL8814AU support to v5.6.4 branch

### PR DESCRIPTION
**Pull request by pecastro**
Hi,

I've done some work _port_ the 8814 code to the v5.6.4 branch.
I'd been having some trouble with the v5.3.4 branch with constant disconnects and couldn't get a host to connect to it in AP at 5GHz, 
It might be a bit rough on the edges ... I had to be creative with missing code and specs but as an exercise which was mainly one of making it work, I'd say it is a success!  :D 

I've tested it works in Managed and AP modes.

Some iperf results from running an AP at 5Ghz 
```
iperf3 -c 192.168.7.1 -t 300 -u -b 0                                                                                                                 
Connecting to host 192.168.7.1, port 5201                                                                                                                                     
[  5] local 192.168.7.98 port 38664 connected to 192.168.7.1 port 5201                                                                                                        
[ ID] Interval           Transfer     Bitrate         Total Datagrams                                                                                                         
[  5]   0.00-1.00   sec  11.0 MBytes  92.2 Mbits/sec  7960                                                                                                                    
[  5]   1.00-2.00   sec  9.02 MBytes  75.6 Mbits/sec  6530                                                                                                                    
[  5]   2.00-3.00   sec  10.7 MBytes  89.9 Mbits/sec  7760                                                                                                                    
[  5]   3.00-4.00   sec  8.76 MBytes  73.4 Mbits/sec  6340                                                                                                                    
[  5]   4.00-5.00   sec  10.7 MBytes  89.4 Mbits/sec  7720                                                                                                                    
[  5]   5.00-6.00   sec  10.6 MBytes  88.7 Mbits/sec  7660 
......
[  5] 296.00-297.00 sec  11.9 MBytes  99.6 Mbits/sec  8600                                                                                                                    
[  5] 297.00-298.00 sec  10.8 MBytes  90.6 Mbits/sec  7820                                                                                                                    
[  5] 298.00-299.00 sec  9.02 MBytes  75.6 Mbits/sec  6530                                                                                                                    
[  5] 299.00-300.00 sec  10.9 MBytes  91.7 Mbits/sec  7920                                                                                                                    
- - - - - - - - - - - - - - - - - - - - - - - - -                                                                                                                             
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams                                                                                          
[  5]   0.00-300.00 sec  2.76 GBytes  79.1 Mbits/sec  0.000 ms  0/2049020 (0%)  sender                                                                                        
[  5]   0.00-300.02 sec  2.76 GBytes  79.1 Mbits/sec  0.080 ms  634/2049020 (0.031%)  receiver   
```

Host system in use for reference:
```
uname -a 
Linux localhost 5.1.8-300.fc30.x86_64 #1 SMP Sun Jun 9 17:09:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Relevant packages:
```
NetworkManager-1.16.2-1.fc30.x86_64
wpa_supplicant-2.8-2.fc30.x86_64
```
lsusb output:
[lsusb.txt](https://github.com/aircrack-ng/rtl8812au/files/3336664/lsusb.txt)

iw list output:
[phy-info-output.txt](https://github.com/aircrack-ng/rtl8812au/files/3336665/phy-info-output.txt)

### CODE REVIEW

**Comment by pecastro** [comment]
@kimocoder Not sure if you've seen this yet but any comments would be greatly appreciated.

**Comment by 0m3rta13** [comment]
Thanks for this. 
Blowing the dust off my Alfa Awus1900 with high hopes (basically unused since buying it a year ago due to its extreme suckiness on any of my Linux security/pentest boxes) 

Would you deem it necessary to remove every trace of all previous attempted driver files or simply rmmod then run this ones dkms or make RTL8814=1? Will be trying all and more but just thought I’d ask. 
Holding thumbs! Will report back!

**Comment by kimocoder** [comment]
I've seen it but i'm a bit busy at work these days. I'll be back soon.

**Comment by kimocoder** [comment]
Btw, the issue with 8814au is that the HAL/phydm is old (ripped out from v5.1.5), therefor the issues with the driver will maintain unfortunately.. @fariouche will also look into adding 8814au and 8821au when he's available, a great developer which is kinda busy atm too

**Comment by pecastro** [comment]
rmmod should be fine. I re-added support to the Makefile to build the driver and bundle it as 88XXau.
So. I would assume it would still work as before...

**Comment by 0m3rta13** [comment]
Well after a few days of playing around, building/installing every way possible, it definitely works. 

Still getting intermittent dropouts in managed mode and lagging/no response in monitor mode BUT not nearly as bad as previous versions and sometimes it works just fine (not 100% but still better) the first time entering monitor mode then a reboot is required if modes are changed thereafter. 

`uname -a
Linux parrot 5.1.0-parrot1-3t-amd64 #1 SMP Parrot 5.1.3-1parrot1.3t (2019-05-20) x86_64 GNU/Linux`

I am wanting to attribute my issues to the fact I still use NetworkManager. So will purge that later and test. I do however have a feeling that these particular problems/hangups are, as @kimocoder has pointed out, due to the crappy old HAL files and no mac80211 support. Either way. This pull is still a win in my book. I shall keep playing around and see if a miracle happens or if Realtek come to the party and give us a decent driver. 

Thanks @pecastro for your efforts here and thanks @kimocoder for all your hard work and valuable time spent on this rather frustrating mess. It really is appreciated.

**Comment by kimocoder** [comment]
Thanks for testing, I don't have time right now but I'll merge if it's working ok, then we may fix issues at a later stage

**Comment by pecastro** [comment]
@0m3rta13 That's great news. Thanks for testing. 
I actually hadn't checked monitor mode as my main use is AP mode.

If you `make CONFIG_RTW_DEBUG=y` you can then insert it with ` modprobe 88XXau rtw_drv_log_level=7` which produces a ton of interesting logs.
I wouldn't mind having a look at the logs if you could catch what happens during those dropouts/lagging you mention.

**Comment by 0m3rta13** [comment]
> @0m3rta13 That's great news. Thanks for testing.
> I actually hadn't checked monitor mode as my main use is AP mode.
> 
> If you `make CONFIG_RTW_DEBUG=y` you can then insert it with ` modprobe 88XXau rtw_drv_log_level=7` which produces a ton of interesting logs.
> I wouldn't mind having a look at the logs if you could catch what happens during those dropouts/lagging you mention.

For sure! got some time on my hands finally so will play around. I see there was a new merge done yesterday so will give both a look and test. If anything interesting shows up i shall let you know

**Comment by fariouche** [comment]
for information, I've just added 8814 support on the 5.6.4.1 branch.
In my case I mainly test in AP mode, was able to achieve 720Mbits (400Mbits real speed)
By default the driver does not advertise any HT or VHT features, don't know why realtek didn't set them, but I've added them and it work fine

**Comment by kimocoder** [comment]
@fariouche added 8814au and 8821au support to v5.6.4.1 branch. I suggest going over to that one. will change default branch and do some tests shortly

**Comment by kimocoder** [comment]
I'll fix the iw output, I know where that issue's at, no problem. :1st_place_medal:

**Comment by 0m3rta13** [comment]
All sounds like good news to me! Of the 3 supported i only have the (black sheep) 8814au (Alfa AWUS1900) so will contribute logs for that through gist (as per the logging levels mentioned above by @pecastro).
Time to make and see what we can break. 

Thanks for the work gents!

**Comment by 0m3rta13** [comment]
Ok been running for a little over 24 hours using with all kinds of modes and usage I could. 
Noob question. Because I seem to have various logs in different places, Which logs are the ones created by setting the above log level and debugging flags? What would be the best way to compile all that is applicable/most helpful, to be posted/pasted on gist?

**Comment by kimocoder** [comment]
@pecastro feel free to tag along on the v5.6.4.1 branch, have been active for some days, but for sure could need some help over here :1st_place_medal: 

I wen't through your PR now.. it's quite some good work you've done!

**Pull request merged**
