### PR TITLE
WIP: Added support for NVIDIA Jetson Nano platform

### LINKED ISSUE #474: Makefile missing NV_NANO option in V5.6.4.2
It looks like this commit adding Jetson Nano options to the Makefile also disappeared https://github.com/aircrack-ng/rtl8812au/commit/2b0fe0c95b4097870ef33ca579343245db5edeb7

### PR DESCRIPTION
**Pull request by sketchybinary**
Partially resolves Issue  #474

### CODE REVIEW

**Comment by sketchybinary** [comment]
Still having float issues

> sketchybinary@localhost:~/rtl8812au$ make
make ARCH=arm64 CROSS_COMPILE= -C /lib/modules/4.9.140-tegra/build M=/home/sketchybinary/rtl8812au  modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.140-tegra-ubuntu18.04_aarch64/kernel-4.9'
  CC [M]  /home/sketchybinary/rtl8812au/core/rtw_cmd.o
gcc: error: unrecognized command line option ‘-mfloat-abi=softfp’
scripts/Makefile.build:335: recipe for target '/home/sketchybinary/rtl8812au/core/rtw_cmd.o' failed
make[2]: *** [/home/sketchybinary/rtl8812au/core/rtw_cmd.o] Error 1
Makefile:1629: recipe for target '_module_/home/sketchybinary/rtl8812au' failed
make[1]: *** [_module_/home/sketchybinary/rtl8812au] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.140-tegra-ubuntu18.04_aarch64/kernel-4.9'
Makefile:2231: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by CGarces** [comment]
Hi.

There is a ARM64 target... CONFIG_PLATFORM_ARM64_RPI ¿not is valid for NVIDIA Jetson Nano?

**Comment by kimocoder** [comment]
Like @CGarces mentioned. Play with that switch/option and let us know if that works out

**Comment by sketchybinary** [comment]
I was still getting the -`mfloat-hard` issue, but I've been looking at other #455 and tried disabling `CONFIG_MP_VHT_HW_TX_MODE` and got the same thing. I noticed that enabling `CONFIG_RTL8821A` and `CONFIG_RTL8814A` (https://github.com/aircrack-ng/rtl8812au/blob/v5.6.4.2/Makefile#L463) so I disabled both of those, and it built through farther.  (I only need RTL8812au).

Next I got the attached error.  I'm going to try fixing the code.
[build1.log](https://github.com/aircrack-ng/rtl8812au/files/3853717/build1.log)

**Comment by sketchybinary** [comment]
The make works, but dkms-install fails. I had to remove some struct members that weren't in the Jetson Nano kernel, but I'm still getting an issue building this.  It looks like the module name is switching from 88XXau to 8812au somewhere.
> sketchybinary@localhost:~/rtl8812au$ sudo ./dkms-install.sh 
> About to run dkms install steps...
> 
> Creating symlink /var/lib/dkms/rtl8812au/5.6.4.2/source ->
>                  /usr/src/rtl8812au-5.6.4.2
> 
> DKMS: add completed.
> 
> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area...
> 'make' -j4 KVER=4.9.140-tegra KSRC=/lib/modules/4.9.140-tegra/build...................................
> ERROR (dkms apport): binary package for rtl8812au: 5.6.4.2 not found
> Error!  Build of 88XXau.ko failed for: 4.9.140-tegra (aarch64)
> Consult the make.log in the build directory
> /var/lib/dkms/rtl8812au/5.6.4.2/build/ for more information.
> 
> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area...
> 'make' -j4 KVER=4.9.140-tegra KSRC=/lib/modules/4.9.140-tegra/build.................................
> ERROR (dkms apport): binary package for rtl8812au: 5.6.4.2 not found
> Error!  Build of 88XXau.ko failed for: 4.9.140-tegra (aarch64)
> Consult the make.log in the build directory
> /var/lib/dkms/rtl8812au/5.6.4.2/build/ for more information.
> Finished running dkms install steps.

**Comment by sketchybinary** [comment]
Okay, this now builds with dkms, loads fine, and I can see all my interfaces.
I'm going to do some testing with kismet, but assuming that goes well, I would like some guidance on what else to do.

I can go and find where the kernel introduced those struct members that I had to `#if` out, but once I get that hammered out, do you mind the change to the driver name?

**Comment by kimocoder** [comment]
"WLAN_DATA_MAXLEN" was added to a Orinoco driver 17 years ago

**Comment by kimocoder** [comment]
Added plattform support for Jetson here https://github.com/aircrack-ng/rtl8812au/commit/b9d50acaa2329a0b54d69ab1aa5195fcc9006ea1

**Comment by CGarces** [comment]
@sketchybinary 
The commit at https://github.com/aircrack-ng/rtl8812au/commit/b9d50acaa2329a0b54d69ab1aa5195fcc9006ea1 works for you?

If not try 
`make CONFIG_PLATFORM_ARM_AARCH64=y CONFIG_PLATFORM_I386_PC=n CONFIG_MP_VHT_HW_TX_MODE=n CONFIG_RTL8814A=n`

And please leave your feedback because we don't have a similar hardware.

**Comment by tranzmatt** [comment]
Was this ever resolved? i'm trying an AC1200 on a Jetson TX2 running 4.9.140-tegra and when I tried the commit and command above, I got:

/home/jetson/Code/WiFi/rtl8812au.b9d50ac/os_dep/osdep_service.c: In function ‘rtw_alloc_etherdev_with_old_priv’:
/home/jetson/Code/WiFi/rtl8812au.b9d50ac/os_dep/osdep_service.c:2392:9: error: ‘struct net_device’ has no member named ‘min_mtu’
  pnetdev->min_mtu = WLAN_MIN_ETHFRM_LEN;
         ^~
/home/jetson/Code/WiFi/rtl8812au.b9d50ac/os_dep/osdep_service.c:2394:9: error: ‘struct net_device’ has no member named ‘max_mtu’
  pnetdev->max_mtu = WLAN_DATA_MAXLEN;
         ^~
/home/jetson/Code/WiFi/rtl8812au.b9d50ac/os_dep/osdep_service.c: In function ‘rtw_alloc_etherdev’:
/home/jetson/Code/WiFi/rtl8812au.b9d50ac/os_dep/osdep_service.c:2417:9: error: ‘struct net_device’ has no member named ‘min_mtu’
  pnetdev->min_mtu = WLAN_MIN_ETHFRM_LEN;

**Pull request closed without merging**
