### PR TITLE
Fixed CONCURRENT mode and enum

### PR DESCRIPTION
**Pull request by fariouche**
- Fixed concurrent mode (8814) to add virtual interfaces (tested 8812 too)
- Fixed enum issue (8812 initialized as 8188E, at least in AP mode)

### CODE REVIEW

**Comment by kimocoder** [comment]
@ZerBea look at @fariouche magic

**Comment by ZerBea** [comment]
Thanks for the notice. Compiled v5.6.4.1 without issues - but I think it doesn't support 8811au devices and crashed:
[  118.531195] rtl88xxau 1-2:1.0 wlp0s20f0u2: renamed from wlan0
[  118.547958] BUG: kernel NULL pointer dereference, address: 00000000000008c0
[  118.547972] #PF: supervisor read access in kernel mode
[  118.547979] #PF: error_code(0x0000) - not-present page
[  118.547985] PGD 0 P4D 0 
[  118.548199] RIP: 0010:rtw_ndev_notifier_call+0x31/0x55 [88XXau]
[  118.548211] Code: d2 74 45 55 53 48 89 f3 48 8b 2a 48 85 ed 74 12 48 89 ef e8 99 fe ff ff 48 83 fb 0b 75 04 84 c0 75 08 b8 00 00 00 00 5b 5d c3 <48> 8b 04 25 c0 08 00 00 48 8d b8 48 45 00 00 ba 10 00 00 00 48 89
[  118.548219] RSP: 0018:ffffa14e444137c0 EFLAGS: 00010202
[  118.548227] RAX: 0000000000000001 RBX: 000000000000000b RCX: ffffffffc0b9f601
[  118.548234] RDX: ffffffffc2489e15 RSI: 000000000000000b RDI: ffff9508a5954000
[  118.548241] RBP: ffff9508a5954000 R08: 0000000000800000 R09: ffffffffb8e9b260
[  118.548247] R10: ffffa14e444137d8 R11: ffffa14e444136c6 R12: 000000000000000b
[  118.548252] R13: ffffa14e44413828 R14: ffffffffb8f07260 R15: 0000000000000000
[  118.548261] FS:  00007f5856cf4840(0000) GS:ffff9508bba00000(0000) knlGS:0000000000000000
[  118.548267] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  118.548273] CR2: 00000000000008c0 CR3: 00000002552ec005 CR4: 00000000003606f0
[  118.548279] Call Trace:
[  118.548305]  notifier_call_chain+0x4c/0x70
[  118.548319]  dev_change_name+0x219/0x320
[  118.548336]  do_setlink+0xd45/0xf10
[  118.548358]  ? get_page_from_freelist+0xc0c/0x1240
[  118.548376]  rtnl_setlink+0x105/0x170
[  118.548405]  rtnetlink_rcv_msg+0x137/0x3c0
[  118.548417]  ? __lookup_slow+0x12e/0x160
[  118.548429]  ? rtnl_calcit.isra.0+0x120/0x120
[  118.548440]  netlink_rcv_skb+0x75/0x140
[  118.548452]  netlink_unicast+0x177/0x1f0
[  118.548463]  netlink_sendmsg+0x1fe/0x3c0
[  118.548478]  sock_sendmsg+0x4f/0x60
[  118.548489]  __sys_sendto+0x120/0x190
[  118.548511]  __x64_sys_sendto+0x25/0x30
[  118.548524]  do_syscall_64+0x5f/0x1d0
[  118.548539]  ? page_fault+0x8/0x30
[  118.548551]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  118.548561] RIP: 0033:0x7f58584f464b
For an 8811 device, the last working driver is v.5.2.20 - this is the bad news.

This is the good news:
The crash made me realize that NETLINK is used to init the device (seems to be a new trend). I noticed the same behavior already on 8188eus. I tested several 8188eus driver (including the last one from Realteks ftp site - need some smaller patches to work on kernel 5.2). All of them running into the same issue (device isn't initialized properly, some ioctl() calls are permitted and some sockaddr_ll flags are ignored).  The consequence of this: missing packets and damaged packets.


BTW:
Running 8812au v5.3.4 on a 811 device, packet injection isn't working.

**Comment by kimocoder** [comment]
v5.3.4 was dropped as newer releases where coming before it for finished up.
Don't have time for testing this week, but I'll be back home next week again :+1:

**Comment by ZerBea** [comment]
Compiled v.5.3.4 only for the reason to determine the differences within the versioning.
Unfortunately, I have not found the real cause yet. Neither on 8812au nor on 8188eus.

**Pull request merged**
